Use one region for aws, eu-west-1
hlesey/kubeadm-vagrant pull request #39
Opened 2021-07-10 19:40 UTC by victorvarza

Use one region, eu-west-1

2021-07-12 11:37 UTC, adriananeci requested changes

2021-07-12 11:37 UTC, adriananeci commented on src/aws/docker/main.tf
> +  dockerhost-name = "dockerhost-${count.index + 1}"
Cred ca e nevoie de `cluster` aici ca sa se coaguleze sub un singur director toate configurile cand facem export

2021-07-12 11:37 UTC, adriananeci commented on src/aws/k8s-empty/main.tf
> +    cluster-empty1 = {
cred ca si aici tre pastrat numele pt compatibilitate export configs. Tre validat.

2021-07-16 08:00 UTC, victorvarza commented on src/aws/docker/main.tf
> +  dockerhost-name = "dockerhost-${count.index + 1}"
e ok, am modificat scriptul de parsare si documentatia de setup: https://github.com/hlesey/k8s-labs-config/blob/main/src/export.py#L96

2021-07-16 08:01 UTC, victorvarza commented on src/aws/k8s-empty/main.tf
> +    cluster-empty1 = {
la fel ca mai sus: https://github.com/hlesey/k8s-labs-config/blob/main/src/export.py#L96.

2021-07-18 18:21 UTC, adriananeci approved these changes

2021-07-18 18:21 UTC, merged