Upgrade k8s to 1.25, cilium to 1.12, and other components
hlesey/kubeadm-vagrant pull request #54
Opened 2022-11-11 18:42 UTC by adriananeci

Needs to be validated and new images mirrored into ghcr registry

2023-01-27 21:50 UTC, adriananeci commented
Logging evidences:
```
❯ k get po -A -owide
NAMESPACE       NAME                                         READY   STATUS      RESTARTS   AGE     IP                NODE                 NOMINATED NODE   READINESS GATES
ingress-nginx   ingress-nginx-admission-create-9nwjw         0/1     Completed   0          2m40s   10.0.0.1          ip-192-168-234-174   <none>           <none>
ingress-nginx   ingress-nginx-admission-patch-f4sdk          0/1     Completed   1          2m40s   10.0.0.70         ip-192-168-234-174   <none>           <none>
ingress-nginx   ingress-nginx-controller-dd994c67-n7hlf      1/1     Running     0          2m40s   10.0.0.98         ip-192-168-234-174   <none>           <none>
kube-system     cilium-8ql8n                                 1/1     Running     0          59s     192.168.234.199   ip-192-168-234-199   <none>           <none>
kube-system     cilium-bjzjf                                 1/1     Running     0          2m40s   192.168.234.174   ip-192-168-234-174   <none>           <none>
kube-system     cilium-kddgl                                 1/1     Running     0          60s     192.168.234.110   ip-192-168-234-110   <none>           <none>
kube-system     cilium-operator-5c594d7766-j6cj2             1/1     Running     0          2m40s   192.168.234.110   ip-192-168-234-110   <none>           <none>
kube-system     cilium-operator-5c594d7766-wt5kp             1/1     Running     0          2m40s   192.168.234.174   ip-192-168-234-174   <none>           <none>
kube-system     coredns-787d4945fb-l7kmq                     1/1     Running     0          2m40s   10.0.0.222        ip-192-168-234-174   <none>           <none>
kube-system     dashboard-metrics-scraper-7bfd588cc9-mqvqw   1/1     Running     0          2m40s   10.0.0.18         ip-192-168-234-174   <none>           <none>
kube-system     etcd-ip-192-168-234-174                      1/1     Running     0          2m53s   192.168.234.174   ip-192-168-234-174   <none>           <none>
kube-system     hubble-relay-745fd8bff5-8p68g                1/1     Running     0          2m40s   10.0.0.171        ip-192-168-234-174   <none>           <none>
kube-system     hubble-ui-55b967c7d6-n5hqg                   2/2     Running     0          2m40s   10.0.0.220        ip-192-168-234-174   <none>           <none>
kube-system     kube-apiserver-ip-192-168-234-174            1/1     Running     0          2m53s   192.168.234.174   ip-192-168-234-174   <none>           <none>
kube-system     kube-controller-manager-ip-192-168-234-174   1/1     Running     0          2m53s   192.168.234.174   ip-192-168-234-174   <none>           <none>
kube-system     kube-proxy-6sbpw                             1/1     Running     0          60s     192.168.234.110   ip-192-168-234-110   <none>           <none>
kube-system     kube-proxy-7m7rg                             1/1     Running     0          59s     192.168.234.199   ip-192-168-234-199   <none>           <none>
kube-system     kube-proxy-rw45j                             1/1     Running     0          2m40s   192.168.234.174   ip-192-168-234-174   <none>           <none>
kube-system     kube-scheduler-ip-192-168-234-174            1/1     Running     0          2m53s   192.168.234.174   ip-192-168-234-174   <none>           <none>
kube-system     kubernetes-dashboard-5767bdd6c-l8p95         1/1     Running     0          2m40s   10.0.0.53         ip-192-168-234-174   <none>           <none>
kube-system     metrics-server-6c86dbcddc-pksq4              1/1     Running     0          2m40s   10.0.0.189        ip-192-168-234-174   <none>           <none>
```

Validated the k8s dashboard too.

2023-01-30 09:06 UTC, victorvarza requested changes

2023-01-30 09:06 UTC, victorvarza commented on src/manifests/ingress/nginx/nginx.yaml
> +  - apiGroups:
Why not just copy/paste from https://github.com/kubernetes/ingress-nginx/blob/main/deploy/static/provider/baremetal/deploy.yaml, without extra indentation?

2023-01-30 09:06 UTC, victorvarza commented on src/manifests/metrics-server/components.yaml
> +  - apiGroups:
Same here. It is easier to follow the changes from upstream.

2023-01-30 09:38 UTC, victorvarza approved these changes

2023-01-30 09:39 UTC, merged